# Generated by Django 3.0.8 on 2020-07-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columamodel',
            options={'ordering': ['nome_coluna'], 'verbose_name': 'Coluna', 'verbose_name_plural': 'Colunas'},
        ),
        migrations.RenameField(
            model_name='columamodel',
            old_name='nomecoluna',
            new_name='nome_coluna',
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_template', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('coluna_direita', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ColumaModel', verbose_name='Coluna Direita')),
                ('coluna_esquerda', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ColumaModel', verbose_name='Coluna Esquerda')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['nome_template'],
            },
        ),
    ]
