# Generated by Django 3.0.8 on 2020-07-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200711_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelDeControleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default=True, upload_to='logo/')),
                ('css_editor', models.TextField(blank=True, null=True)),
                ('js_editor', models.TextField(blank=True, null=True)),
                ('font_editor', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
