# Generated by Django 3.0.8 on 2020-07-11 20:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conteudo', '0003_auto_20200711_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('thumbnail', models.ImageField(blank=True, default=True, upload_to='jogo/thumb')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag_fk', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudo.TagModel', verbose_name='Tags ')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
