# Generated by Django 3.0.8 on 2020-07-11 20:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloJogoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='jogo/capitulo')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now)),
                ('chave_estrangeira', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='detonado.JogoModel', verbose_name='Jogo ')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
