# Generated by Django 3.0.8 on 2020-07-12 04:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0002_capitulojogomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulojogomodel',
            options={'ordering': ['nome'], 'verbose_name': 'Capítulo do jogo', 'verbose_name_plural': 'Capítulos dos jogos'},
        ),
        migrations.AlterModelOptions(
            name='jogomodel',
            options={'ordering': ['nome'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterField(
            model_name='capitulojogomodel',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Conteúdo'),
        ),
    ]
