# Generated by Django 3.0.8 on 2020-07-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0003_auto_20200712_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloDeJogoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlataformaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='jogomodel',
            name='ano_lancamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogomodel',
            name='desenvolvido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
