# Generated by Django 3.0.8 on 2020-07-13 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0004_auto_20200712_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estilodejogomodel',
            options={'ordering': ['nome'], 'verbose_name': 'Estilo de jogo', 'verbose_name_plural': 'Estilo de jogo'},
        ),
        migrations.AlterModelOptions(
            name='plataformamodel',
            options={'ordering': ['nome'], 'verbose_name': 'Jogado em', 'verbose_name_plural': 'jogado em'},
        ),
    ]
