# Generated by Django 3.0.8 on 2020-07-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0005_auto_20200712_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogomodel',
            name='estitlo_de_jogo_fk',
            field=models.ManyToManyField(to='detonado.EstiloDeJogoModel', verbose_name='Estilo De Jogo'),
        ),
        migrations.AddField(
            model_name='jogomodel',
            name='plataforma_fk',
            field=models.ManyToManyField(to='detonado.PlataformaModel', verbose_name='Plataforma do jogo'),
        ),
    ]
