# Generated by Django 3.0.8 on 2020-07-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0006_auto_20200712_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogomodel',
            name='ano_lancamento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jogomodel',
            name='estitlo_de_jogo_fk',
            field=models.ManyToManyField(blank=True, null=True, to='detonado.EstiloDeJogoModel', verbose_name='Estilo De Jogo'),
        ),
        migrations.AlterField(
            model_name='jogomodel',
            name='plataforma_fk',
            field=models.ManyToManyField(blank=True, null=True, to='detonado.PlataformaModel', verbose_name='Plataforma do jogo'),
        ),
    ]
