# Generated by Django 3.0.8 on 2020-07-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0007_auto_20200712_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plataformamodel',
            options={'ordering': ['nome'], 'verbose_name': 'plataforma', 'verbose_name_plural': 'plataforma em'},
        ),
        migrations.AddField(
            model_name='capitulojogomodel',
            name='tipo_fase',
            field=models.CharField(choices=[('H', 'História'), ('S', 'Secundária'), ('C', 'Conquista')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
