# Generated by Django 3.0.8 on 2020-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0008_auto_20200721_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulojogomodel',
            name='tipo_fase',
            field=models.CharField(choices=[('H', 'História'), ('S', 'Secundária'), ('C', 'Conquista')], default='H', max_length=1),
        ),
    ]
