# Generated by Django 3.0.8 on 2020-08-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detonado', '0009_auto_20200721_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogomodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
