# Generated by Django 3.0.8 on 2020-07-11 19:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_paginamodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginamodel',
            options={'ordering': ['nome_pagina'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterField(
            model_name='paginamodel',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Conteúdo'),
        ),
    ]
