# Generated by Django 3.0.8 on 2020-08-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_auto_20200711_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginamodel',
            options={'ordering': ['nome'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.RemoveField(
            model_name='paginamodel',
            name='nome_pagina',
        ),
        migrations.AddField(
            model_name='paginamodel',
            name='nome',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paginamodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
